// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEventsService.proto

package ba.unsa.etf.grpc;

public interface ActionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ba.unsa.etf.grpc.ActionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string timestamp_akcije = 1;</code>
   */
  java.lang.String getTimestampAkcije();
  /**
   * <code>string timestamp_akcije = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimestampAkcijeBytes();

  /**
   * <code>string naziv_mikroservisa = 2;</code>
   */
  java.lang.String getNazivMikroservisa();
  /**
   * <code>string naziv_mikroservisa = 2;</code>
   */
  com.google.protobuf.ByteString
      getNazivMikroservisaBytes();

  /**
   * <code>string resurs = 3;</code>
   */
  java.lang.String getResurs();
  /**
   * <code>string resurs = 3;</code>
   */
  com.google.protobuf.ByteString
      getResursBytes();

  /**
   * <code>.ba.unsa.etf.grpc.ActionRequest.TipAkcije tip_akcije = 4;</code>
   */
  int getTipAkcijeValue();
  /**
   * <code>.ba.unsa.etf.grpc.ActionRequest.TipAkcije tip_akcije = 4;</code>
   */
  ba.unsa.etf.grpc.ActionRequest.TipAkcije getTipAkcije();

  /**
   * <code>.ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju tip_odgovora_na_akciju = 5;</code>
   */
  int getTipOdgovoraNaAkcijuValue();
  /**
   * <code>.ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju tip_odgovora_na_akciju = 5;</code>
   */
  ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju getTipOdgovoraNaAkciju();
}
