// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEventsService.proto

package ba.unsa.etf.grpc;

public final class SystemEventsServiceOuterClass {
  private SystemEventsServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ba_unsa_etf_grpc_ActionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ba_unsa_etf_grpc_ActionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ba_unsa_etf_grpc_ActionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ba_unsa_etf_grpc_ActionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SystemEventsService.proto\022\020ba.unsa.etf" +
      ".grpc\"\370\002\n\rActionRequest\022\030\n\020timestamp_akc" +
      "ije\030\001 \001(\t\022\032\n\022naziv_mikroservisa\030\002 \001(\t\022\016\n" +
      "\006resurs\030\003 \001(\t\022=\n\ntip_akcije\030\004 \001(\0162).ba.u" +
      "nsa.etf.grpc.ActionRequest.TipAkcije\022S\n\026" +
      "tip_odgovora_na_akciju\030\005 \001(\01623.ba.unsa.e" +
      "tf.grpc.ActionRequest.TipOdgovoraNaAkcij" +
      "u\"I\n\tTipAkcije\022\017\n\013NEPOZNATTIP\020\000\022\n\n\006CREAT" +
      "E\020\001\022\n\n\006DELETE\020\002\022\007\n\003GET\020\003\022\n\n\006UPDATE\020\004\"B\n\023" +
      "TipOdgovoraNaAkciju\022\023\n\017NEPOZNATODGOVOR\020\000",
      "\022\n\n\006USPJEH\020\001\022\n\n\006GRESKA\020\002\" \n\016ActionRespon" +
      "se\022\016\n\006poruka\030\001 \001(\t2k\n\023SystemEventsServic" +
      "e\022T\n\017registrujAkciju\022\037.ba.unsa.etf.grpc." +
      "ActionRequest\032 .ba.unsa.etf.grpc.ActionR" +
      "esponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ba_unsa_etf_grpc_ActionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ba_unsa_etf_grpc_ActionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ba_unsa_etf_grpc_ActionRequest_descriptor,
        new java.lang.String[] { "TimestampAkcije", "NazivMikroservisa", "Resurs", "TipAkcije", "TipOdgovoraNaAkciju", });
    internal_static_ba_unsa_etf_grpc_ActionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ba_unsa_etf_grpc_ActionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ba_unsa_etf_grpc_ActionResponse_descriptor,
        new java.lang.String[] { "Poruka", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
