// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEventsService.proto

package ba.unsa.etf.grpc;

/**
 * Protobuf type {@code ba.unsa.etf.grpc.ActionResponse}
 */
public  final class ActionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ba.unsa.etf.grpc.ActionResponse)
    ActionResponseOrBuilder {
  // Use ActionResponse.newBuilder() to construct.
  private ActionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActionResponse() {
    poruka_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ActionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            poruka_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ba.unsa.etf.grpc.SystemEventsServiceOuterClass.internal_static_ba_unsa_etf_grpc_ActionResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ba.unsa.etf.grpc.SystemEventsServiceOuterClass.internal_static_ba_unsa_etf_grpc_ActionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ba.unsa.etf.grpc.ActionResponse.class, ba.unsa.etf.grpc.ActionResponse.Builder.class);
  }

  public static final int PORUKA_FIELD_NUMBER = 1;
  private volatile java.lang.Object poruka_;
  /**
   * <code>string poruka = 1;</code>
   */
  public java.lang.String getPoruka() {
    java.lang.Object ref = poruka_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      poruka_ = s;
      return s;
    }
  }
  /**
   * <code>string poruka = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPorukaBytes() {
    java.lang.Object ref = poruka_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      poruka_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPorukaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, poruka_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPorukaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, poruka_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ba.unsa.etf.grpc.ActionResponse)) {
      return super.equals(obj);
    }
    ba.unsa.etf.grpc.ActionResponse other = (ba.unsa.etf.grpc.ActionResponse) obj;

    boolean result = true;
    result = result && getPoruka()
        .equals(other.getPoruka());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PORUKA_FIELD_NUMBER;
    hash = (53 * hash) + getPoruka().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ba.unsa.etf.grpc.ActionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ba.unsa.etf.grpc.ActionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ba.unsa.etf.grpc.ActionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ba.unsa.etf.grpc.ActionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ba.unsa.etf.grpc.ActionResponse)
      ba.unsa.etf.grpc.ActionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ba.unsa.etf.grpc.SystemEventsServiceOuterClass.internal_static_ba_unsa_etf_grpc_ActionResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ba.unsa.etf.grpc.SystemEventsServiceOuterClass.internal_static_ba_unsa_etf_grpc_ActionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ba.unsa.etf.grpc.ActionResponse.class, ba.unsa.etf.grpc.ActionResponse.Builder.class);
    }

    // Construct using ba.unsa.etf.grpc.ActionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      poruka_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ba.unsa.etf.grpc.SystemEventsServiceOuterClass.internal_static_ba_unsa_etf_grpc_ActionResponse_descriptor;
    }

    public ba.unsa.etf.grpc.ActionResponse getDefaultInstanceForType() {
      return ba.unsa.etf.grpc.ActionResponse.getDefaultInstance();
    }

    public ba.unsa.etf.grpc.ActionResponse build() {
      ba.unsa.etf.grpc.ActionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ba.unsa.etf.grpc.ActionResponse buildPartial() {
      ba.unsa.etf.grpc.ActionResponse result = new ba.unsa.etf.grpc.ActionResponse(this);
      result.poruka_ = poruka_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ba.unsa.etf.grpc.ActionResponse) {
        return mergeFrom((ba.unsa.etf.grpc.ActionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ba.unsa.etf.grpc.ActionResponse other) {
      if (other == ba.unsa.etf.grpc.ActionResponse.getDefaultInstance()) return this;
      if (!other.getPoruka().isEmpty()) {
        poruka_ = other.poruka_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ba.unsa.etf.grpc.ActionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ba.unsa.etf.grpc.ActionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object poruka_ = "";
    /**
     * <code>string poruka = 1;</code>
     */
    public java.lang.String getPoruka() {
      java.lang.Object ref = poruka_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        poruka_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string poruka = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPorukaBytes() {
      java.lang.Object ref = poruka_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        poruka_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string poruka = 1;</code>
     */
    public Builder setPoruka(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      poruka_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string poruka = 1;</code>
     */
    public Builder clearPoruka() {
      
      poruka_ = getDefaultInstance().getPoruka();
      onChanged();
      return this;
    }
    /**
     * <code>string poruka = 1;</code>
     */
    public Builder setPorukaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      poruka_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ba.unsa.etf.grpc.ActionResponse)
  }

  // @@protoc_insertion_point(class_scope:ba.unsa.etf.grpc.ActionResponse)
  private static final ba.unsa.etf.grpc.ActionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ba.unsa.etf.grpc.ActionResponse();
  }

  public static ba.unsa.etf.grpc.ActionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActionResponse>
      PARSER = new com.google.protobuf.AbstractParser<ActionResponse>() {
    public ActionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ActionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActionResponse> getParserForType() {
    return PARSER;
  }

  public ba.unsa.etf.grpc.ActionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

