// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEventsService.proto

package ba.unsa.etf.grpc;

/**
 * Protobuf type {@code ba.unsa.etf.grpc.ActionRequest}
 */
public  final class ActionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ba.unsa.etf.grpc.ActionRequest)
    ActionRequestOrBuilder {
  // Use ActionRequest.newBuilder() to construct.
  private ActionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActionRequest() {
    timestampAkcije_ = "";
    nazivMikroservisa_ = "";
    resurs_ = "";
    tipAkcije_ = 0;
    tipOdgovoraNaAkciju_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ActionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            timestampAkcije_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            nazivMikroservisa_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            resurs_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            tipAkcije_ = rawValue;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            tipOdgovoraNaAkciju_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ba.unsa.etf.grpc.SystemEventsServiceOuterClass.internal_static_ba_unsa_etf_grpc_ActionRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ba.unsa.etf.grpc.SystemEventsServiceOuterClass.internal_static_ba_unsa_etf_grpc_ActionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ba.unsa.etf.grpc.ActionRequest.class, ba.unsa.etf.grpc.ActionRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code ba.unsa.etf.grpc.ActionRequest.TipAkcije}
   */
  public enum TipAkcije
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NEPOZNATTIP = 0;</code>
     */
    NEPOZNATTIP(0),
    /**
     * <code>CREATE = 1;</code>
     */
    CREATE(1),
    /**
     * <code>DELETE = 2;</code>
     */
    DELETE(2),
    /**
     * <code>GET = 3;</code>
     */
    GET(3),
    /**
     * <code>UPDATE = 4;</code>
     */
    UPDATE(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NEPOZNATTIP = 0;</code>
     */
    public static final int NEPOZNATTIP_VALUE = 0;
    /**
     * <code>CREATE = 1;</code>
     */
    public static final int CREATE_VALUE = 1;
    /**
     * <code>DELETE = 2;</code>
     */
    public static final int DELETE_VALUE = 2;
    /**
     * <code>GET = 3;</code>
     */
    public static final int GET_VALUE = 3;
    /**
     * <code>UPDATE = 4;</code>
     */
    public static final int UPDATE_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TipAkcije valueOf(int value) {
      return forNumber(value);
    }

    public static TipAkcije forNumber(int value) {
      switch (value) {
        case 0: return NEPOZNATTIP;
        case 1: return CREATE;
        case 2: return DELETE;
        case 3: return GET;
        case 4: return UPDATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TipAkcije>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TipAkcije> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TipAkcije>() {
            public TipAkcije findValueByNumber(int number) {
              return TipAkcije.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ba.unsa.etf.grpc.ActionRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final TipAkcije[] VALUES = values();

    public static TipAkcije valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TipAkcije(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ba.unsa.etf.grpc.ActionRequest.TipAkcije)
  }

  /**
   * Protobuf enum {@code ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju}
   */
  public enum TipOdgovoraNaAkciju
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NEPOZNATODGOVOR = 0;</code>
     */
    NEPOZNATODGOVOR(0),
    /**
     * <code>USPJEH = 1;</code>
     */
    USPJEH(1),
    /**
     * <code>GRESKA = 2;</code>
     */
    GRESKA(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NEPOZNATODGOVOR = 0;</code>
     */
    public static final int NEPOZNATODGOVOR_VALUE = 0;
    /**
     * <code>USPJEH = 1;</code>
     */
    public static final int USPJEH_VALUE = 1;
    /**
     * <code>GRESKA = 2;</code>
     */
    public static final int GRESKA_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TipOdgovoraNaAkciju valueOf(int value) {
      return forNumber(value);
    }

    public static TipOdgovoraNaAkciju forNumber(int value) {
      switch (value) {
        case 0: return NEPOZNATODGOVOR;
        case 1: return USPJEH;
        case 2: return GRESKA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TipOdgovoraNaAkciju>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TipOdgovoraNaAkciju> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TipOdgovoraNaAkciju>() {
            public TipOdgovoraNaAkciju findValueByNumber(int number) {
              return TipOdgovoraNaAkciju.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ba.unsa.etf.grpc.ActionRequest.getDescriptor().getEnumTypes().get(1);
    }

    private static final TipOdgovoraNaAkciju[] VALUES = values();

    public static TipOdgovoraNaAkciju valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TipOdgovoraNaAkciju(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju)
  }

  public static final int TIMESTAMP_AKCIJE_FIELD_NUMBER = 1;
  private volatile java.lang.Object timestampAkcije_;
  /**
   * <code>string timestamp_akcije = 1;</code>
   */
  public java.lang.String getTimestampAkcije() {
    java.lang.Object ref = timestampAkcije_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestampAkcije_ = s;
      return s;
    }
  }
  /**
   * <code>string timestamp_akcije = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTimestampAkcijeBytes() {
    java.lang.Object ref = timestampAkcije_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestampAkcije_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAZIV_MIKROSERVISA_FIELD_NUMBER = 2;
  private volatile java.lang.Object nazivMikroservisa_;
  /**
   * <code>string naziv_mikroservisa = 2;</code>
   */
  public java.lang.String getNazivMikroservisa() {
    java.lang.Object ref = nazivMikroservisa_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nazivMikroservisa_ = s;
      return s;
    }
  }
  /**
   * <code>string naziv_mikroservisa = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNazivMikroservisaBytes() {
    java.lang.Object ref = nazivMikroservisa_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nazivMikroservisa_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESURS_FIELD_NUMBER = 3;
  private volatile java.lang.Object resurs_;
  /**
   * <code>string resurs = 3;</code>
   */
  public java.lang.String getResurs() {
    java.lang.Object ref = resurs_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resurs_ = s;
      return s;
    }
  }
  /**
   * <code>string resurs = 3;</code>
   */
  public com.google.protobuf.ByteString
      getResursBytes() {
    java.lang.Object ref = resurs_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resurs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIP_AKCIJE_FIELD_NUMBER = 4;
  private int tipAkcije_;
  /**
   * <code>.ba.unsa.etf.grpc.ActionRequest.TipAkcije tip_akcije = 4;</code>
   */
  public int getTipAkcijeValue() {
    return tipAkcije_;
  }
  /**
   * <code>.ba.unsa.etf.grpc.ActionRequest.TipAkcije tip_akcije = 4;</code>
   */
  public ba.unsa.etf.grpc.ActionRequest.TipAkcije getTipAkcije() {
    ba.unsa.etf.grpc.ActionRequest.TipAkcije result = ba.unsa.etf.grpc.ActionRequest.TipAkcije.valueOf(tipAkcije_);
    return result == null ? ba.unsa.etf.grpc.ActionRequest.TipAkcije.UNRECOGNIZED : result;
  }

  public static final int TIP_ODGOVORA_NA_AKCIJU_FIELD_NUMBER = 5;
  private int tipOdgovoraNaAkciju_;
  /**
   * <code>.ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju tip_odgovora_na_akciju = 5;</code>
   */
  public int getTipOdgovoraNaAkcijuValue() {
    return tipOdgovoraNaAkciju_;
  }
  /**
   * <code>.ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju tip_odgovora_na_akciju = 5;</code>
   */
  public ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju getTipOdgovoraNaAkciju() {
    ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju result = ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju.valueOf(tipOdgovoraNaAkciju_);
    return result == null ? ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTimestampAkcijeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timestampAkcije_);
    }
    if (!getNazivMikroservisaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nazivMikroservisa_);
    }
    if (!getResursBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resurs_);
    }
    if (tipAkcije_ != ba.unsa.etf.grpc.ActionRequest.TipAkcije.NEPOZNATTIP.getNumber()) {
      output.writeEnum(4, tipAkcije_);
    }
    if (tipOdgovoraNaAkciju_ != ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju.NEPOZNATODGOVOR.getNumber()) {
      output.writeEnum(5, tipOdgovoraNaAkciju_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTimestampAkcijeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timestampAkcije_);
    }
    if (!getNazivMikroservisaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nazivMikroservisa_);
    }
    if (!getResursBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resurs_);
    }
    if (tipAkcije_ != ba.unsa.etf.grpc.ActionRequest.TipAkcije.NEPOZNATTIP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, tipAkcije_);
    }
    if (tipOdgovoraNaAkciju_ != ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju.NEPOZNATODGOVOR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, tipOdgovoraNaAkciju_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ba.unsa.etf.grpc.ActionRequest)) {
      return super.equals(obj);
    }
    ba.unsa.etf.grpc.ActionRequest other = (ba.unsa.etf.grpc.ActionRequest) obj;

    boolean result = true;
    result = result && getTimestampAkcije()
        .equals(other.getTimestampAkcije());
    result = result && getNazivMikroservisa()
        .equals(other.getNazivMikroservisa());
    result = result && getResurs()
        .equals(other.getResurs());
    result = result && tipAkcije_ == other.tipAkcije_;
    result = result && tipOdgovoraNaAkciju_ == other.tipOdgovoraNaAkciju_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_AKCIJE_FIELD_NUMBER;
    hash = (53 * hash) + getTimestampAkcije().hashCode();
    hash = (37 * hash) + NAZIV_MIKROSERVISA_FIELD_NUMBER;
    hash = (53 * hash) + getNazivMikroservisa().hashCode();
    hash = (37 * hash) + RESURS_FIELD_NUMBER;
    hash = (53 * hash) + getResurs().hashCode();
    hash = (37 * hash) + TIP_AKCIJE_FIELD_NUMBER;
    hash = (53 * hash) + tipAkcije_;
    hash = (37 * hash) + TIP_ODGOVORA_NA_AKCIJU_FIELD_NUMBER;
    hash = (53 * hash) + tipOdgovoraNaAkciju_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ba.unsa.etf.grpc.ActionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ba.unsa.etf.grpc.ActionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ba.unsa.etf.grpc.ActionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ba.unsa.etf.grpc.ActionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ba.unsa.etf.grpc.ActionRequest)
      ba.unsa.etf.grpc.ActionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ba.unsa.etf.grpc.SystemEventsServiceOuterClass.internal_static_ba_unsa_etf_grpc_ActionRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ba.unsa.etf.grpc.SystemEventsServiceOuterClass.internal_static_ba_unsa_etf_grpc_ActionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ba.unsa.etf.grpc.ActionRequest.class, ba.unsa.etf.grpc.ActionRequest.Builder.class);
    }

    // Construct using ba.unsa.etf.grpc.ActionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      timestampAkcije_ = "";

      nazivMikroservisa_ = "";

      resurs_ = "";

      tipAkcije_ = 0;

      tipOdgovoraNaAkciju_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ba.unsa.etf.grpc.SystemEventsServiceOuterClass.internal_static_ba_unsa_etf_grpc_ActionRequest_descriptor;
    }

    public ba.unsa.etf.grpc.ActionRequest getDefaultInstanceForType() {
      return ba.unsa.etf.grpc.ActionRequest.getDefaultInstance();
    }

    public ba.unsa.etf.grpc.ActionRequest build() {
      ba.unsa.etf.grpc.ActionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ba.unsa.etf.grpc.ActionRequest buildPartial() {
      ba.unsa.etf.grpc.ActionRequest result = new ba.unsa.etf.grpc.ActionRequest(this);
      result.timestampAkcije_ = timestampAkcije_;
      result.nazivMikroservisa_ = nazivMikroservisa_;
      result.resurs_ = resurs_;
      result.tipAkcije_ = tipAkcije_;
      result.tipOdgovoraNaAkciju_ = tipOdgovoraNaAkciju_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ba.unsa.etf.grpc.ActionRequest) {
        return mergeFrom((ba.unsa.etf.grpc.ActionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ba.unsa.etf.grpc.ActionRequest other) {
      if (other == ba.unsa.etf.grpc.ActionRequest.getDefaultInstance()) return this;
      if (!other.getTimestampAkcije().isEmpty()) {
        timestampAkcije_ = other.timestampAkcije_;
        onChanged();
      }
      if (!other.getNazivMikroservisa().isEmpty()) {
        nazivMikroservisa_ = other.nazivMikroservisa_;
        onChanged();
      }
      if (!other.getResurs().isEmpty()) {
        resurs_ = other.resurs_;
        onChanged();
      }
      if (other.tipAkcije_ != 0) {
        setTipAkcijeValue(other.getTipAkcijeValue());
      }
      if (other.tipOdgovoraNaAkciju_ != 0) {
        setTipOdgovoraNaAkcijuValue(other.getTipOdgovoraNaAkcijuValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ba.unsa.etf.grpc.ActionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ba.unsa.etf.grpc.ActionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object timestampAkcije_ = "";
    /**
     * <code>string timestamp_akcije = 1;</code>
     */
    public java.lang.String getTimestampAkcije() {
      java.lang.Object ref = timestampAkcije_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestampAkcije_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timestamp_akcije = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampAkcijeBytes() {
      java.lang.Object ref = timestampAkcije_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestampAkcije_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timestamp_akcije = 1;</code>
     */
    public Builder setTimestampAkcije(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timestampAkcije_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp_akcije = 1;</code>
     */
    public Builder clearTimestampAkcije() {
      
      timestampAkcije_ = getDefaultInstance().getTimestampAkcije();
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp_akcije = 1;</code>
     */
    public Builder setTimestampAkcijeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timestampAkcije_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nazivMikroservisa_ = "";
    /**
     * <code>string naziv_mikroservisa = 2;</code>
     */
    public java.lang.String getNazivMikroservisa() {
      java.lang.Object ref = nazivMikroservisa_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nazivMikroservisa_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string naziv_mikroservisa = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNazivMikroservisaBytes() {
      java.lang.Object ref = nazivMikroservisa_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nazivMikroservisa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string naziv_mikroservisa = 2;</code>
     */
    public Builder setNazivMikroservisa(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nazivMikroservisa_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string naziv_mikroservisa = 2;</code>
     */
    public Builder clearNazivMikroservisa() {
      
      nazivMikroservisa_ = getDefaultInstance().getNazivMikroservisa();
      onChanged();
      return this;
    }
    /**
     * <code>string naziv_mikroservisa = 2;</code>
     */
    public Builder setNazivMikroservisaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nazivMikroservisa_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object resurs_ = "";
    /**
     * <code>string resurs = 3;</code>
     */
    public java.lang.String getResurs() {
      java.lang.Object ref = resurs_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resurs_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resurs = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResursBytes() {
      java.lang.Object ref = resurs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resurs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resurs = 3;</code>
     */
    public Builder setResurs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resurs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string resurs = 3;</code>
     */
    public Builder clearResurs() {
      
      resurs_ = getDefaultInstance().getResurs();
      onChanged();
      return this;
    }
    /**
     * <code>string resurs = 3;</code>
     */
    public Builder setResursBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resurs_ = value;
      onChanged();
      return this;
    }

    private int tipAkcije_ = 0;
    /**
     * <code>.ba.unsa.etf.grpc.ActionRequest.TipAkcije tip_akcije = 4;</code>
     */
    public int getTipAkcijeValue() {
      return tipAkcije_;
    }
    /**
     * <code>.ba.unsa.etf.grpc.ActionRequest.TipAkcije tip_akcije = 4;</code>
     */
    public Builder setTipAkcijeValue(int value) {
      tipAkcije_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ba.unsa.etf.grpc.ActionRequest.TipAkcije tip_akcije = 4;</code>
     */
    public ba.unsa.etf.grpc.ActionRequest.TipAkcije getTipAkcije() {
      ba.unsa.etf.grpc.ActionRequest.TipAkcije result = ba.unsa.etf.grpc.ActionRequest.TipAkcije.valueOf(tipAkcije_);
      return result == null ? ba.unsa.etf.grpc.ActionRequest.TipAkcije.UNRECOGNIZED : result;
    }
    /**
     * <code>.ba.unsa.etf.grpc.ActionRequest.TipAkcije tip_akcije = 4;</code>
     */
    public Builder setTipAkcije(ba.unsa.etf.grpc.ActionRequest.TipAkcije value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      tipAkcije_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ba.unsa.etf.grpc.ActionRequest.TipAkcije tip_akcije = 4;</code>
     */
    public Builder clearTipAkcije() {
      
      tipAkcije_ = 0;
      onChanged();
      return this;
    }

    private int tipOdgovoraNaAkciju_ = 0;
    /**
     * <code>.ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju tip_odgovora_na_akciju = 5;</code>
     */
    public int getTipOdgovoraNaAkcijuValue() {
      return tipOdgovoraNaAkciju_;
    }
    /**
     * <code>.ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju tip_odgovora_na_akciju = 5;</code>
     */
    public Builder setTipOdgovoraNaAkcijuValue(int value) {
      tipOdgovoraNaAkciju_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju tip_odgovora_na_akciju = 5;</code>
     */
    public ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju getTipOdgovoraNaAkciju() {
      ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju result = ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju.valueOf(tipOdgovoraNaAkciju_);
      return result == null ? ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju.UNRECOGNIZED : result;
    }
    /**
     * <code>.ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju tip_odgovora_na_akciju = 5;</code>
     */
    public Builder setTipOdgovoraNaAkciju(ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      tipOdgovoraNaAkciju_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ba.unsa.etf.grpc.ActionRequest.TipOdgovoraNaAkciju tip_odgovora_na_akciju = 5;</code>
     */
    public Builder clearTipOdgovoraNaAkciju() {
      
      tipOdgovoraNaAkciju_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ba.unsa.etf.grpc.ActionRequest)
  }

  // @@protoc_insertion_point(class_scope:ba.unsa.etf.grpc.ActionRequest)
  private static final ba.unsa.etf.grpc.ActionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ba.unsa.etf.grpc.ActionRequest();
  }

  public static ba.unsa.etf.grpc.ActionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActionRequest>
      PARSER = new com.google.protobuf.AbstractParser<ActionRequest>() {
    public ActionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ActionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActionRequest> getParserForType() {
    return PARSER;
  }

  public ba.unsa.etf.grpc.ActionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

