// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEventsService.proto

package ba.unsa.etf.grpc;

public interface ActionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ba.unsa.etf.grpc.ActionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string poruka = 1;</code>
   */
  java.lang.String getPoruka();
  /**
   * <code>string poruka = 1;</code>
   */
  com.google.protobuf.ByteString
      getPorukaBytes();
}
